version: 2.1
orbs:
  backend_deploy: an-vui/backend-service-orb@1.0.6

workflows:
  build_and_deploy:
    jobs:
      # Build and push Docker image
      - backend_deploy/docker_build_push:
          name: build-and-push
          image_repo: 'thanhlcm90/ncc-admin-app-new'
          node_flags: '--max-old-space-size=4096'
          build_args: '--build-arg BUILDKIT_INLINE_CACHE=1'
          context:
            - docker
          filters:
            branches:
              only:
                - develop
                - main

      # Deploy to Development
      - backend_deploy/update_service:
          name: deploy-develop
          webhook_url_env: 'NCC_ADMIN_APP_NEW_DEV'
          secret_key_env: 'SECRET_KEY'
          service_name: 'NCC Admin App New Service'
          environment: 'development'
          context:
            - portainer
            - jira
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - develop
          post-steps:
            - backend_deploy/notify_jira:
                environment_type: development
                job_type: deployment
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>

      # Deploy to main Production
      - backend_deploy/update_service:
          name: deploy-main
          webhook_url_env: 'NCC_ADMIN_APP_NEW_PROD'
          secret_key_env: 'SECRET_KEY'
          service_name: 'NCC Admin App New Service'
          environment: 'production'
          context:
            - portainer
            - jira
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - main
          post-steps:
            - backend_deploy/notify_jira:
                environment_type: production
                job_type: deployment
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
