import { z } from "zod";

export const filmFormSchema = z.object({
  // Required fields
  filmName: z.string().min(1, {
    error: "Tên phim là bắt buộc",
  }),
  videoUrl: z.string().min(1, {
    error: "Link video là bắt buộc",
  }),
  duration: z.number().positive({
    error: "Thời lượng phải là số dương",
  }),

  // Optional fields
  id: z.number().optional(),
  filmNameEn: z.string().optional(),
  countryId: z.number().optional(),
  director: z.string().optional(),
  actors: z.string().optional(),
  introduction: z.string().optional(),
  manufacturerId: z.union([z.string(), z.number()]).optional(),
  versionCode: z.string().optional(),
  statusCode: z.string().optional(),
  languageCode: z.string().optional(),
  holding: z.union([z.boolean(), z.string()]).optional(),
  description: z.string().optional(),
  sellOnline: z.boolean().optional(),
  metaDescription: z.string().optional(),
  metaKeyword: z.string().optional(),
  metaTitle: z.string().optional(),
  limitedToStores: z.boolean().optional(),
  subjectToAcl: z.boolean().optional(),
  createdOnUtc: z.string().optional(),
  updatedOnUtc: z.string().optional(),
  published: z.boolean().optional(),
  deleted: z.boolean().optional(),
  pictureId: z.number().optional(),
  imageUrl: z.string().optional(),
  premieredDay: z.union([z.date(), z.string()]).optional(),
  showOnHomePage: z.boolean().optional(),
  tags: z.string().optional(),
  allowCustomerReviews: z.boolean().optional(),
  approvedRatingSum: z.number().optional(),
  notApprovedRatingSum: z.number().optional(),
  approvedTotalReviews: z.number().optional(),
  notApprovedTotalReviews: z.number().optional(),
  totalLike: z.number().optional(),
  numberOfViews: z.number().optional(),
  isHot: z.union([z.boolean(), z.number()]).optional(),
  ageAbove: z.number().optional(),
  proposedPrice: z.number().optional(),
  trailerOnHomePage: z.boolean().optional(),
  orderNo: z.number().optional(),
  sellOnlineBefore: z.number().optional(),
  createdUser: z.string().optional(),
  updatedUser: z.string().optional(),
  isFree: z.union([z.boolean(), z.string()]).optional(),
  categoryIds: z.array(z.number()).optional(),
  filmStatus: z.any().optional(),
  filmVersion: z.any().optional(),
  filmLanguage: z.any().optional(),
});

export type FilmFormInput = z.infer<typeof filmFormSchema>;
